### ISSUE TITLE
Problem with GS Example.ipynb: Error with CF.fit

### ISSUE THREAD

**Issue by vincentthouvenotTH** [thibaultlaugel/growingspheres#1]
Hello
I was running the example given by the jupyter notebook GS Example.ipynb. When running it (without any change), I have following errors: 
```
cf_list = []
cnt = 0
X_test_class0 = X_test[np.where(y_test == 0)]
for obs in X_test_class0:
    print('====================================================', cnt)
    CF = cf.CounterfactualExplanation(obs, clf.predict, method='GS')
    CF.fit(n_in_layer=20, first_radius=0.1, dicrease_radius=10, sparse=True, verbose=True)#)
    cf_list.append(CF.enemy)
    cnt += 1
cf_list = np.array(cf_list) 

```
Error:
----> 7     CF.fit(n_in_layer=20, first_radius=0.1, dicrease_radius=10, sparse=True, verbose=True)#)
---> 44         self.enemy = cf.find_counterfactual()
---> 57         ennemies_ = self.exploration()
---> 76             first_layer_ = self.ennemies_in_layer_((0, radius_), self.caps, self.n_in_layer)
--> 105         layer = generate_inside_ball(self.obs_to_interprete, segment, n)
growingspheres/utils/gs_utils.py in generate_inside_ball(center, segment, n)
     24     def norm(v):
     25         return np.linalg.norm(v, ord=2, axis=1)
---> 26     d = center.shape[1]
     27     z = np.random.normal(0, 1, (n, d))
     28     u = np.random.uniform(segment[0]**d, segment[1]**d, n)

IndexError: tuple index out of range

Do you have any idea where this error may have come from?

Thank you,
Best regards

**Comment by Weiting-Gao** [comment]
Hello, I have the same issue, have you found a way to solve it?

**Comment by thibaultlaugel** [comment]
Hello, sorry for the delay in answers. 

The issue was simply that "obs" had to be reshaped. I added a new notebook with a simple example, which works. Tell me if this is alright with you. I encountered another bug on the sparse=True parameter, I will be fixing this asap.

Thanks for your comments
